# Generated by Django 6.0.6 on 2026-07-03 01:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_cookie', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compra',
            options={'ordering': ['-data']},
        ),
        migrations.AlterModelOptions(
            name='formapagamento',
            options={'ordering': ['nome'], 'verbose_name': 'Forma de Pagamento', 'verbose_name_plural': 'Formas de Pagamento'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='itemcompra',
            options={'verbose_name': 'Item da Compra', 'verbose_name_plural': 'Itens de Compra'},
        ),
        migrations.AlterModelOptions(
            name='tipopagamento',
            options={'ordering': ['nome'], 'verbose_name': 'Tipo', 'verbose_name_plural': 'Tipos'},
        ),
        migrations.AlterField(
            model_name='formapagamento',
            name='nome',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='tipopagamento',
            name='nome',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
