# Generated by Django 6.0.6 on 2026-07-06 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_cookie', '0004_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída'), ('VENDA', 'Venda'), ('COMPRA', 'Compra'), ('PRODUTO', 'Produto'), ('CLIENTE', 'Cliente')], max_length=20)),
                ('descricao', models.CharField(max_length=255)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('referencia_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
