version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: finance_cookie_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=finance_cookie
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=cookie_secret_pass # Senha isolada do banco do Docker
    ports:
      - "5434:5432" # Expõe na porta 5434 para não dar conflito se você já tiver o Postgres local rodando

  web:
    build: .
    container_name: finance_cookie_backend
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SECRET_KEY=replace-with-your-secret-key
      - DJANGO_DEBUG=True
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,web
      - DJANGO_DB_ENGINE=django.db.backends.postgresql
      - DJANGO_DB_NAME=finance_cookie
      - DJANGO_DB_USER=postgres
      - DJANGO_DB_PASSWORD=cookie_secret_pass
      - DJANGO_DB_HOST=db # Aponta para o serviço do banco acima
      - DJANGO_DB_PORT=5432
      - CORS_ALLOWED_ORIGINS=http://localhost:19006,http://127.0.0.1:19006
    depends_on:
      - db

volumes:
  postgres_data: