sonar.projectKey=finance-cookie
sonar.projectName=Finance Cookie
sonar.projectVersion=0.1.0

# Encoding do código fonte (Garante leitura universal em UTF-8)
sonar.sourceEncoding=UTF-8

sonar.sources=.
sonar.sources.inclusions=**/**.py
sonar.exclusions=**/tests/**, docs/**, sigarte/**, **/static/**, **/templates/**, **/migrations/**, **/__pycache__/**, **/admin.py, **/__init__.*, manage.py

# FIX: Define a versão exata e única do Python usada no Docker do projeto
sonar.python.version=3.11

sonar.scm.provider=git

# Coverage / Unit Tests
sonar.tests=.
sonar.test.inclusions=**/test_**.py, **/tests_**.py, **/tests.py

sonar.python.coverage.reportPaths=/tmp/coverage.xml